#!/bin/sh
set -e

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database /usr/share/applications || true
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -f /usr/share/icons/hicolor || true
fi

if command -v xdg-mime >/dev/null 2>&1; then
  xdg-mime default mezon.desktop x-scheme-handler/mezonapp || true
fi
